title: Vinicius Cabral
logo: /assets/img/Headshotfile.jpg
description: Hi, I'm Vinicius Cabral.<br>Data Analyst student at NCI.<br>Passionate about turning data into actionable insights and solving problems through data.
#show_downloads: true
theme: jekyll-theme-minimal
