title: Vinicius Carrarini 
logo: /assets/img/Headshotfile.jpg
description: Hi, I'm Vinicius Cabral.<br>Data Analystics student at NCI.<br>Passionate about turning data into actionable insights and solving problems through data.
#show_downloads: true
theme: jekyll-theme-minimal
social:
  linkedin: https://www.linkedin.com/in/viniciuscarrarini/
